language: cpp
sudo: required
dist: trusty
cache:
  directories:
    - build/external
compiler:
  - clang
  - gcc
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/64463f491a9781e3b19b
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never # default: always
install:
  - sudo apt-get install libboost-thread-dev1.59.0 libboost-date-time1.59.0 libboost-filesystem1.59.0 libboost-system1.59.0 libboost-regex1.59.0
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y
  - sudo apt-get install -y g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - gcc --version
  - cmake --version
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG  
script:
  - cmake --build .
  - ctest -V -C debug
  - ./fuzzy-database& 
  - cd ../ #Back to project root to run npm test
  - npm install && npm test

